/**
 * Public configuration contract for the widget.
 *
 * A host page configures the widget either by setting `window.FinBridgeChatConfig`
 * before the script loads, or by calling `FinBridgeChat.init(config)` manually.
 */

export interface FinBridgeChatConfig {
  /**
   * Base URL of the FinBridge AI backend, e.g. "https://api.finbridge.example".
   * The widget calls `${apiUrl}/ai/chat/message`. Required.
   */
  apiUrl: string;

  // ── Authentication (pick ONE) ──────────────────────────────────────────────
  // The backend protects /ai/chat/message with a Bearer token. Supply it via
  // exactly one of the three options below.

  /** A static bearer token. Simplest, but the token is visible in page source. */
  token?: string;

  /**
   * A function that returns a token (or a Promise of one). Called before each
   * request, so it can refresh expiring tokens. Best for production.
   */
  getToken?: () => string | Promise<string>;

  /**
   * URL the widget GETs to obtain a token. Expects JSON `{ "token": "..." }`.
   * Useful when your own server mints short-lived tokens for anonymous visitors.
   */
  tokenUrl?: string;

  // ── Branding & copy ────────────────────────────────────────────────────────

  /** Title shown in the chat panel header. Default: "RAY". */
  title?: string;

  /** Short tagline under the title in the launcher card. */
  subtitle?: string;

  /** Text on the floating launcher button. Default: "Ask RAY". */
  launcherLabel?: string;

  /** First assistant message shown when the panel opens. */
  welcomeMessage?: string;

  /** Quick-reply chips shown before the first user message. */
  suggestions?: string[];

  /** Placeholder for the message input. Default: "Type your question here…". */
  placeholder?: string;

  /** Small disclaimer under the input. Default: "All responses are generated by AI". */
  footerText?: string;

  /** URL/inline SVG/emoji for the brand mark. Falls back to a built-in icon. */
  logoUrl?: string;

  // ── Appearance ───────────────────────────────────────────────────────────────

  /** Primary brand color (hex). Default: "#3d5afe". */
  primaryColor?: string;

  /** Corner the widget docks to. Default: "bottom-right". */
  position?: 'bottom-right' | 'bottom-left';

  /** Distance from the page edges, in pixels. Default: 24. */
  offset?: number;

  /** Stacking order of the widget root. Default: 2147483000. */
  zIndex?: number;

  // ── Behaviour ────────────────────────────────────────────────────────────────

  /** Open the panel automatically on first load. Default: false. */
  autoOpen?: boolean;

  /**
   * Persist the conversation id in localStorage so the thread continues across
   * page loads. Default: true. Set false for fully stateless sessions.
   */
  persistConversation?: boolean;

  /** Namespace for localStorage keys, in case multiple widgets coexist. Default: "finbridge". */
  storageKey?: string;

  /** Called whenever the panel opens. */
  onOpen?: () => void;

  /** Called whenever the panel closes. */
  onClose?: () => void;

  /** Called after every successful reply. */
  onMessage?: (msg: { role: 'user' | 'assistant'; text: string }) => void;
}

export type ResolvedConfig = Required<
  Omit<FinBridgeChatConfig, 'token' | 'getToken' | 'tokenUrl' | 'logoUrl' | 'subtitle' | 'onOpen' | 'onClose' | 'onMessage'>
> &
  Pick<FinBridgeChatConfig, 'token' | 'getToken' | 'tokenUrl' | 'logoUrl' | 'subtitle' | 'onOpen' | 'onClose' | 'onMessage'>;

const DEFAULTS: Omit<ResolvedConfig, 'apiUrl'> = {
  title: 'FinBridge',
  launcherLabel: 'Ask FinBridge',
  welcomeMessage:
    "Hi! 👋 I'm FinBridge AI. Ask me anything, or pick one of the options below to get started.",
  suggestions: [
    'What can you help me with?',
    'Show me recent activity',
    'How do I get started?',
  ],
  placeholder: 'Type your question here…',
  footerText: 'All responses are generated by AI',
  primaryColor: '#dc2626',
  position: 'bottom-right',
  offset: 24,
  zIndex: 2147483000,
  autoOpen: false,
  persistConversation: true,
  storageKey: 'finbridge',
  // optionals left undefined below
  subtitle: undefined,
  logoUrl: undefined,
  token: undefined,
  getToken: undefined,
  tokenUrl: undefined,
  onOpen: undefined,
  onClose: undefined,
  onMessage: undefined,
};

/** Merge user config over defaults and validate the essentials. */
export function resolveConfig(input: FinBridgeChatConfig): ResolvedConfig {
  if (!input || typeof input.apiUrl !== 'string' || !input.apiUrl) {
    throw new Error('[FinBridgeChat] config.apiUrl is required, e.g. { apiUrl: "https://api.example.com" }');
  }
  // Strip a trailing slash so `${apiUrl}/ai/chat/message` is always well-formed.
  const apiUrl = input.apiUrl.replace(/\/+$/, '');

  if (!input.token && !input.getToken && !input.tokenUrl) {
    console.warn(
      '[FinBridgeChat] No token/getToken/tokenUrl provided. ' +
        'Requests to a protected backend will fail with 401.',
    );
  }

  return { ...DEFAULTS, ...input, apiUrl };
}
